### ISSUE TITLE
Windows version crashing on Windows 10

### ISSUE THREAD

**Issue by Stanestane** [adenzu/Manga-Panel-Extractor#3] opened 2024-03-20 17:28 UTC
Unfortunately, the precompiled windows version seems to crash on Windows 10. It doesn't even open the GUI. The window just blinks for a fraction of a second and closes.

**Comment by adenzu** [comment] 2024-03-20 18:41
Duplicate of [issue#4](https://github.com/adenzu/Manga-Panel-Extractor/issues/4)

**Closed by adenzu** 2024-03-20 18:41 UTC
Labels: duplicate
